services:
  - type: web
    name: web-api
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: web_api_db
          property: connectionString

databases:
  - name: web_api_db
    ipAllowList: [] 